# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Travelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=30)),
                ('from_place', models.CharField(max_length=30)),
                ('to_place', models.CharField(max_length=30)),
                ('depart_at_from', models.TimeField()),
                ('arrival_at_to', models.TimeField()),
                ('seat_no', models.IntegerField()),
                ('available', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('off', models.IntegerField()),
                ('collected', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='Travelling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.Travelling'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
