# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelling',
            old_name='flight',
            new_name='Bus',
        ),
    ]
